// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssignableContentRevision = `-- name: GetAssignableContentRevision :one
SELECT cr.revision_id, cr.semantic_payload
FROM content_revisions cr
JOIN content_use_states us ON us.content_revision_id = cr.revision_id
JOIN validation_decisions vd ON vd.validation_decision_id = us.current_validation_decision_id
WHERE cr.revision_id = $1
  AND us.assignment_eligible = true
  AND us.operational_state = 'ACTIVE'
  AND vd.result = 'PASS'
  AND vd.validation_policy_version = 'bootstrap-reading-training-v1'
FOR SHARE
`

type GetAssignableContentRevisionRow struct {
	RevisionID      string
	SemanticPayload []byte
}

func (q *Queries) GetAssignableContentRevision(ctx context.Context, revisionID string) (GetAssignableContentRevisionRow, error) {
	row := q.db.QueryRow(ctx, getAssignableContentRevision, revisionID)
	var i GetAssignableContentRevisionRow
	err := row.Scan(&i.RevisionID, &i.SemanticPayload)
	return i, err
}

const getPracticeActivity = `-- name: GetPracticeActivity :one
SELECT pa.content_revision_id, pa.assigned_at, cr.semantic_payload
FROM practice_activities pa
JOIN content_revisions cr ON cr.revision_id = pa.content_revision_id
WHERE pa.practice_activity_id = $1
  AND pa.learner_id = $2
`

type GetPracticeActivityParams struct {
	PracticeActivityID string
	LearnerID          string
}

type GetPracticeActivityRow struct {
	ContentRevisionID string
	AssignedAt        pgtype.Timestamptz
	SemanticPayload   []byte
}

func (q *Queries) GetPracticeActivity(ctx context.Context, arg GetPracticeActivityParams) (GetPracticeActivityRow, error) {
	row := q.db.QueryRow(ctx, getPracticeActivity, arg.PracticeActivityID, arg.LearnerID)
	var i GetPracticeActivityRow
	err := row.Scan(&i.ContentRevisionID, &i.AssignedAt, &i.SemanticPayload)
	return i, err
}

const insertPracticeActivity = `-- name: InsertPracticeActivity :exec
INSERT INTO practice_activities (
  practice_activity_id,
  learner_id,
  content_revision_id,
  feature_id,
  practice_mode_id,
  primary_activity_purpose,
  evidence_candidacy,
  test_variant
)
VALUES ($1, $2, $3, 'R-F04', 'PM-R03', 'TRAINING', 'NOT_EVIDENCE_CANDIDATE', 'ACADEMIC')
`

type InsertPracticeActivityParams struct {
	PracticeActivityID string
	LearnerID          string
	ContentRevisionID  string
}

func (q *Queries) InsertPracticeActivity(ctx context.Context, arg InsertPracticeActivityParams) error {
	_, err := q.db.Exec(ctx, insertPracticeActivity, arg.PracticeActivityID, arg.LearnerID, arg.ContentRevisionID)
	return err
}
