// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempt.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const evaluateAttempt = `-- name: EvaluateAttempt :execrows
UPDATE attempts
SET status = 'EVALUATED',
    resource_revision = resource_revision + 1,
    submitted_answers = $3,
    response_payload = $4,
    actual_conditions_payload = $5,
    raw_score = $6,
    max_score = $7,
    submitted_at = $8,
    evaluated_at = $8
WHERE attempt_id = $1 AND learner_id = $2 AND status = 'DRAFT' AND resource_revision = $9
`

type EvaluateAttemptParams struct {
	AttemptID               string
	LearnerID               string
	SubmittedAnswers        []byte
	ResponsePayload         []byte
	ActualConditionsPayload []byte
	RawScore                *int32
	MaxScore                *int32
	SubmittedAt             pgtype.Timestamptz
	ResourceRevision        int64
}

func (q *Queries) EvaluateAttempt(ctx context.Context, arg EvaluateAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, evaluateAttempt,
		arg.AttemptID,
		arg.LearnerID,
		arg.SubmittedAnswers,
		arg.ResponsePayload,
		arg.ActualConditionsPayload,
		arg.RawScore,
		arg.MaxScore,
		arg.SubmittedAt,
		arg.ResourceRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivityForAttempt = `-- name: GetActivityForAttempt :one
SELECT content_revision_id, primary_activity_purpose
FROM practice_activities
WHERE practice_activity_id = $1 AND learner_id = $2
`

type GetActivityForAttemptParams struct {
	PracticeActivityID string
	LearnerID          string
}

type GetActivityForAttemptRow struct {
	ContentRevisionID      string
	PrimaryActivityPurpose string
}

func (q *Queries) GetActivityForAttempt(ctx context.Context, arg GetActivityForAttemptParams) (GetActivityForAttemptRow, error) {
	row := q.db.QueryRow(ctx, getActivityForAttempt, arg.PracticeActivityID, arg.LearnerID)
	var i GetActivityForAttemptRow
	err := row.Scan(&i.ContentRevisionID, &i.PrimaryActivityPurpose)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT practice_activity_id, content_revision_id, status, resource_revision, created_at, submitted_at, evaluated_at, response_payload, actual_conditions_payload
FROM attempts
WHERE attempt_id = $1 AND learner_id = $2
`

type GetAttemptParams struct {
	AttemptID string
	LearnerID string
}

type GetAttemptRow struct {
	PracticeActivityID      string
	ContentRevisionID       string
	Status                  string
	ResourceRevision        int64
	CreatedAt               pgtype.Timestamptz
	SubmittedAt             pgtype.Timestamptz
	EvaluatedAt             pgtype.Timestamptz
	ResponsePayload         []byte
	ActualConditionsPayload []byte
}

func (q *Queries) GetAttempt(ctx context.Context, arg GetAttemptParams) (GetAttemptRow, error) {
	row := q.db.QueryRow(ctx, getAttempt, arg.AttemptID, arg.LearnerID)
	var i GetAttemptRow
	err := row.Scan(
		&i.PracticeActivityID,
		&i.ContentRevisionID,
		&i.Status,
		&i.ResourceRevision,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.EvaluatedAt,
		&i.ResponsePayload,
		&i.ActualConditionsPayload,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO attempts (attempt_id, learner_id, practice_activity_id, content_revision_id, status, resource_revision)
VALUES ($1, $2, $3, $4, 'DRAFT', 1)
`

type InsertAttemptParams struct {
	AttemptID          string
	LearnerID          string
	PracticeActivityID string
	ContentRevisionID  string
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.AttemptID,
		arg.LearnerID,
		arg.PracticeActivityID,
		arg.ContentRevisionID,
	)
	return err
}

const insertObservation = `-- name: InsertObservation :exec
INSERT INTO observations (observation_id, attempt_id, learner_id, content_revision_id, result_payload, conditions_payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertObservationParams struct {
	ObservationID     string
	AttemptID         string
	LearnerID         string
	ContentRevisionID string
	ResultPayload     []byte
	ConditionsPayload []byte
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.Exec(ctx, insertObservation,
		arg.ObservationID,
		arg.AttemptID,
		arg.LearnerID,
		arg.ContentRevisionID,
		arg.ResultPayload,
		arg.ConditionsPayload,
		arg.CreatedAt,
	)
	return err
}

const lockAttemptForSubmission = `-- name: LockAttemptForSubmission :one
SELECT a.status, a.resource_revision, a.content_revision_id, pa.primary_activity_purpose, cr.semantic_payload
FROM attempts a
JOIN practice_activities pa ON pa.practice_activity_id = a.practice_activity_id
JOIN content_revisions cr ON cr.revision_id = a.content_revision_id
WHERE a.attempt_id = $1 AND a.learner_id = $2
FOR UPDATE OF a
`

type LockAttemptForSubmissionParams struct {
	AttemptID string
	LearnerID string
}

type LockAttemptForSubmissionRow struct {
	Status                 string
	ResourceRevision       int64
	ContentRevisionID      string
	PrimaryActivityPurpose string
	SemanticPayload        []byte
}

func (q *Queries) LockAttemptForSubmission(ctx context.Context, arg LockAttemptForSubmissionParams) (LockAttemptForSubmissionRow, error) {
	row := q.db.QueryRow(ctx, lockAttemptForSubmission, arg.AttemptID, arg.LearnerID)
	var i LockAttemptForSubmissionRow
	err := row.Scan(
		&i.Status,
		&i.ResourceRevision,
		&i.ContentRevisionID,
		&i.PrimaryActivityPurpose,
		&i.SemanticPayload,
	)
	return i, err
}
