// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcdb

import (
	"context"
)

const claimIdempotency = `-- name: ClaimIdempotency :one
INSERT INTO idempotency_operations (learner_id, operation, idempotency_key, payload_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING 1
`

type ClaimIdempotencyParams struct {
	LearnerID      string
	Operation      string
	IdempotencyKey string
	PayloadHash    []byte
}

func (q *Queries) ClaimIdempotency(ctx context.Context, arg ClaimIdempotencyParams) (int32, error) {
	row := q.db.QueryRow(ctx, claimIdempotency,
		arg.LearnerID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.PayloadHash,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockIdempotency = `-- name: LockIdempotency :one
SELECT payload_hash, outcome_resource_id, outcome_payload
FROM idempotency_operations
WHERE learner_id = $1
  AND operation = $2
  AND idempotency_key = $3
FOR UPDATE
`

type LockIdempotencyParams struct {
	LearnerID      string
	Operation      string
	IdempotencyKey string
}

type LockIdempotencyRow struct {
	PayloadHash       []byte
	OutcomeResourceID *string
	OutcomePayload    []byte
}

func (q *Queries) LockIdempotency(ctx context.Context, arg LockIdempotencyParams) (LockIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, lockIdempotency, arg.LearnerID, arg.Operation, arg.IdempotencyKey)
	var i LockIdempotencyRow
	err := row.Scan(&i.PayloadHash, &i.OutcomeResourceID, &i.OutcomePayload)
	return i, err
}

const setIdempotencyOutcome = `-- name: SetIdempotencyOutcome :execrows
UPDATE idempotency_operations
SET outcome_resource_id = $4
WHERE learner_id = $1
  AND operation = $2
  AND idempotency_key = $3
`

type SetIdempotencyOutcomeParams struct {
	LearnerID         string
	Operation         string
	IdempotencyKey    string
	OutcomeResourceID *string
}

func (q *Queries) SetIdempotencyOutcome(ctx context.Context, arg SetIdempotencyOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIdempotencyOutcome,
		arg.LearnerID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.OutcomeResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIdempotencyPayload = `-- name: SetIdempotencyPayload :execrows
UPDATE idempotency_operations
SET outcome_payload = $4
WHERE learner_id = $1
  AND operation = $2
  AND idempotency_key = $3
`

type SetIdempotencyPayloadParams struct {
	LearnerID      string
	Operation      string
	IdempotencyKey string
	OutcomePayload []byte
}

func (q *Queries) SetIdempotencyPayload(ctx context.Context, arg SetIdempotencyPayloadParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIdempotencyPayload,
		arg.LearnerID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.OutcomePayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
