// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	AttemptID          string
	LearnerID          string
	PracticeActivityID string
	ContentRevisionID  string
	Status             string
	ResourceRevision   int64
	SubmittedAnswers   []byte
	RawScore           *int32
	MaxScore           *int32
	SubmittedAt        pgtype.Timestamptz
	EvaluatedAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type Content struct {
	ContentID string
	CreatedAt pgtype.Timestamptz
}

type ContentRevision struct {
	RevisionID       string
	ContentID        string
	SemanticPayload  []byte
	ContentHash      string
	OriginProvenance []byte
	CreatedAt        pgtype.Timestamptz
}

type ContentUseState struct {
	ContentRevisionID           string
	CurrentValidationDecisionID string
	OperationalState            string
	AssignmentEligible          bool
	UpdatedAt                   pgtype.Timestamptz
}

type EvidenceFact struct {
	EvidenceFactID    string
	ObservationID     string
	LearnerID         string
	ClaimScope        []byte
	EligibilityStatus string
	EligibilityReason string
	InferenceScope    string
	PolicyVersion     string
	AdmittedAt        pgtype.Timestamptz
}

type IdempotencyOperation struct {
	LearnerID         string
	Operation         string
	IdempotencyKey    string
	PayloadHash       []byte
	OutcomeResourceID *string
	CreatedAt         pgtype.Timestamptz
}

type Learner struct {
	LearnerID string
	CreatedAt pgtype.Timestamptz
}

type Observation struct {
	ObservationID     string
	AttemptID         string
	LearnerID         string
	ContentRevisionID string
	ResultPayload     []byte
	ConditionsPayload []byte
	CreatedAt         pgtype.Timestamptz
}

type PracticeActivity struct {
	PracticeActivityID     string
	LearnerID              string
	ContentRevisionID      string
	FeatureID              string
	PracticeModeID         string
	PrimaryActivityPurpose string
	EvidenceCandidacy      string
	TestVariant            string
	AssignedAt             pgtype.Timestamptz
	AssessmentTypeID       *string
}

type Session struct {
	SessionID   string
	LearnerID   string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type TargetProfile struct {
	LearnerID            string
	TestVariant          string
	TargetOverallBand    *float64
	MinimumListeningBand *float64
	MinimumReadingBand   *float64
	MinimumWritingBand   *float64
	MinimumSpeakingBand  *float64
	ResourceRevision     int64
	UpdatedAt            pgtype.Timestamptz
}

type ValidationDecision struct {
	ValidationDecisionID    string
	ContentRevisionID       string
	ValidationPolicyVersion string
	IntendedUse             string
	Result                  string
	Findings                []byte
	EvaluatedAt             pgtype.Timestamptz
}
