// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyPlanItemForAssignment = `-- name: GetDailyPlanItemForAssignment :one
SELECT
  dpi.content_revision_id,
  dpi.validation_decision_id,
  dpi.validation_policy_version,
  dpi.validation_intended_use,
  dpi.planned_operational_state,
  dpi.planned_assignment_eligible,
  dp.target_profile_revision
FROM daily_plan_items dpi
JOIN daily_plans dp ON dp.daily_plan_id = dpi.daily_plan_id
WHERE dpi.plan_item_id = $1
  AND dp.learner_id = $2
`

type GetDailyPlanItemForAssignmentParams struct {
	PlanItemID string
	LearnerID  string
}

type GetDailyPlanItemForAssignmentRow struct {
	ContentRevisionID         string
	ValidationDecisionID      string
	ValidationPolicyVersion   string
	ValidationIntendedUse     string
	PlannedOperationalState   string
	PlannedAssignmentEligible bool
	TargetProfileRevision     *int64
}

func (q *Queries) GetDailyPlanItemForAssignment(ctx context.Context, arg GetDailyPlanItemForAssignmentParams) (GetDailyPlanItemForAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getDailyPlanItemForAssignment, arg.PlanItemID, arg.LearnerID)
	var i GetDailyPlanItemForAssignmentRow
	err := row.Scan(
		&i.ContentRevisionID,
		&i.ValidationDecisionID,
		&i.ValidationPolicyVersion,
		&i.ValidationIntendedUse,
		&i.PlannedOperationalState,
		&i.PlannedAssignmentEligible,
		&i.TargetProfileRevision,
	)
	return i, err
}

const getSampledReadingAssessmentForPlanning = `-- name: GetSampledReadingAssessmentForPlanning :one
SELECT
  cr.revision_id,
  cr.semantic_payload,
  us.current_validation_decision_id,
  us.operational_state,
  us.assignment_eligible,
  vd.validation_policy_version,
  vd.intended_use
FROM content_revisions cr
JOIN content_use_states us ON us.content_revision_id = cr.revision_id
JOIN validation_decisions vd ON vd.validation_decision_id = us.current_validation_decision_id
WHERE cr.revision_id = 'reading-bootstrap-assessment-001-r1'
  AND us.assignment_eligible = true
  AND us.operational_state = 'ACTIVE'
  AND vd.result = 'PASS'
  AND vd.validation_policy_version = 'bootstrap-reading-assessment-v1'
  AND vd.intended_use = 'ASSESSMENT_SAMPLED_CLASSIFICATION'
`

type GetSampledReadingAssessmentForPlanningRow struct {
	RevisionID                  string
	SemanticPayload             []byte
	CurrentValidationDecisionID string
	OperationalState            string
	AssignmentEligible          bool
	ValidationPolicyVersion     string
	IntendedUse                 string
}

func (q *Queries) GetSampledReadingAssessmentForPlanning(ctx context.Context) (GetSampledReadingAssessmentForPlanningRow, error) {
	row := q.db.QueryRow(ctx, getSampledReadingAssessmentForPlanning)
	var i GetSampledReadingAssessmentForPlanningRow
	err := row.Scan(
		&i.RevisionID,
		&i.SemanticPayload,
		&i.CurrentValidationDecisionID,
		&i.OperationalState,
		&i.AssignmentEligible,
		&i.ValidationPolicyVersion,
		&i.IntendedUse,
	)
	return i, err
}

const hasAdmittedSampledReadingEvidence = `-- name: HasAdmittedSampledReadingEvidence :one
SELECT EXISTS (
  SELECT 1
  FROM evidence_facts ef
  JOIN observations o ON o.observation_id = ef.observation_id
  WHERE ef.learner_id = $1
    AND o.content_revision_id = 'reading-bootstrap-assessment-001-r1'
    AND ef.claim_scope->>'assessment_type_id' = 'AT-02'
    AND ef.claim_scope->>'test_variant' = 'Academic'
    AND ef.claim_scope->'canonical_target_ids' = '["R-QT-02","R-QT-03"]'::jsonb
    AND ef.claim_scope->'content_context_ids' = '["CTX-READING-ACADEMIC"]'::jsonb
    AND ef.claim_scope->'official_family_ids' = '["IELTS-R-QF-02","IELTS-R-QF-03"]'::jsonb
)
`

func (q *Queries) HasAdmittedSampledReadingEvidence(ctx context.Context, learnerID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdmittedSampledReadingEvidence, learnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasPriorSampledReadingAssignment = `-- name: HasPriorSampledReadingAssignment :one
SELECT EXISTS (
  SELECT 1
  FROM practice_activities
  WHERE learner_id = $1
    AND content_revision_id = 'reading-bootstrap-assessment-001-r1'
    AND primary_activity_purpose = 'ASSESSMENT'
)
`

func (q *Queries) HasPriorSampledReadingAssignment(ctx context.Context, learnerID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPriorSampledReadingAssignment, learnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAssessmentPracticeActivity = `-- name: InsertAssessmentPracticeActivity :one
INSERT INTO practice_activities (
  practice_activity_id,
  learner_id,
  content_revision_id,
  feature_id,
  practice_mode_id,
  primary_activity_purpose,
  evidence_candidacy,
  assessment_type_id,
  test_variant,
  daily_plan_item_id
)
VALUES ($1, $2, $3, 'R-F04', 'PM-R03', 'ASSESSMENT', 'ASSESSMENT_MAY_ADMIT', 'AT-02', 'ACADEMIC', $4)
ON CONFLICT DO NOTHING
RETURNING assigned_at
`

type InsertAssessmentPracticeActivityParams struct {
	PracticeActivityID string
	LearnerID          string
	ContentRevisionID  string
	DailyPlanItemID    *string
}

func (q *Queries) InsertAssessmentPracticeActivity(ctx context.Context, arg InsertAssessmentPracticeActivityParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertAssessmentPracticeActivity,
		arg.PracticeActivityID,
		arg.LearnerID,
		arg.ContentRevisionID,
		arg.DailyPlanItemID,
	)
	var assigned_at pgtype.Timestamptz
	err := row.Scan(&assigned_at)
	return assigned_at, err
}

const insertDailyPlan = `-- name: InsertDailyPlan :exec
INSERT INTO daily_plans (
  daily_plan_id,
  learner_id,
  target_profile_revision,
  target_context_payload,
  unresolved_target_conditions_payload,
  coverage_gaps_payload,
  generated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDailyPlanParams struct {
	DailyPlanID                       string
	LearnerID                         string
	TargetProfileRevision             *int64
	TargetContextPayload              []byte
	UnresolvedTargetConditionsPayload []byte
	CoverageGapsPayload               []byte
	GeneratedAt                       pgtype.Timestamptz
}

func (q *Queries) InsertDailyPlan(ctx context.Context, arg InsertDailyPlanParams) error {
	_, err := q.db.Exec(ctx, insertDailyPlan,
		arg.DailyPlanID,
		arg.LearnerID,
		arg.TargetProfileRevision,
		arg.TargetContextPayload,
		arg.UnresolvedTargetConditionsPayload,
		arg.CoverageGapsPayload,
		arg.GeneratedAt,
	)
	return err
}

const insertDailyPlanItem = `-- name: InsertDailyPlanItem :exec
INSERT INTO daily_plan_items (
  plan_item_id,
  daily_plan_id,
  content_revision_id,
  validation_decision_id,
  validation_policy_version,
  validation_intended_use,
  planned_operational_state,
  planned_assignment_eligible,
  reason_code,
  created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'INSUFFICIENT_EVIDENCE', $9)
`

type InsertDailyPlanItemParams struct {
	PlanItemID                string
	DailyPlanID               string
	ContentRevisionID         string
	ValidationDecisionID      string
	ValidationPolicyVersion   string
	ValidationIntendedUse     string
	PlannedOperationalState   string
	PlannedAssignmentEligible bool
	CreatedAt                 pgtype.Timestamptz
}

func (q *Queries) InsertDailyPlanItem(ctx context.Context, arg InsertDailyPlanItemParams) error {
	_, err := q.db.Exec(ctx, insertDailyPlanItem,
		arg.PlanItemID,
		arg.DailyPlanID,
		arg.ContentRevisionID,
		arg.ValidationDecisionID,
		arg.ValidationPolicyVersion,
		arg.ValidationIntendedUse,
		arg.PlannedOperationalState,
		arg.PlannedAssignmentEligible,
		arg.CreatedAt,
	)
	return err
}
