// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principal.sql

package sqlcdb

import (
	"context"
)

const getExternalPrincipal = `-- name: GetExternalPrincipal :one
SELECT actor_id, learner_id
FROM external_principals
WHERE provider = $1
  AND external_issuer = $2
  AND external_subject = $3
`

type GetExternalPrincipalParams struct {
	Provider        string
	ExternalIssuer  string
	ExternalSubject string
}

type GetExternalPrincipalRow struct {
	ActorID   string
	LearnerID string
}

func (q *Queries) GetExternalPrincipal(ctx context.Context, arg GetExternalPrincipalParams) (GetExternalPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getExternalPrincipal, arg.Provider, arg.ExternalIssuer, arg.ExternalSubject)
	var i GetExternalPrincipalRow
	err := row.Scan(&i.ActorID, &i.LearnerID)
	return i, err
}

const insertExternalPrincipal = `-- name: InsertExternalPrincipal :exec
INSERT INTO external_principals (provider, external_issuer, external_subject, actor_id, learner_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertExternalPrincipalParams struct {
	Provider        string
	ExternalIssuer  string
	ExternalSubject string
	ActorID         string
	LearnerID       string
}

func (q *Queries) InsertExternalPrincipal(ctx context.Context, arg InsertExternalPrincipalParams) error {
	_, err := q.db.Exec(ctx, insertExternalPrincipal,
		arg.Provider,
		arg.ExternalIssuer,
		arg.ExternalSubject,
		arg.ActorID,
		arg.LearnerID,
	)
	return err
}

const insertLearner = `-- name: InsertLearner :exec
INSERT INTO learners (learner_id) VALUES ($1)
`

func (q *Queries) InsertLearner(ctx context.Context, learnerID string) error {
	_, err := q.db.Exec(ctx, insertLearner, learnerID)
	return err
}

const lockExternalPrincipal = `-- name: LockExternalPrincipal :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockExternalPrincipal(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockExternalPrincipal, lockKey)
	return err
}
