// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateSession = `-- name: AuthenticateSession :one
SELECT learner_id
FROM sessions
WHERE token_digest = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) AuthenticateSession(ctx context.Context, tokenDigest []byte) (string, error) {
	row := q.db.QueryRow(ctx, authenticateSession, tokenDigest)
	var learner_id string
	err := row.Scan(&learner_id)
	return learner_id, err
}

const insertLearner = `-- name: InsertLearner :exec
INSERT INTO learners (learner_id) VALUES ($1)
`

func (q *Queries) InsertLearner(ctx context.Context, learnerID string) error {
	_, err := q.db.Exec(ctx, insertLearner, learnerID)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (session_id, learner_id, token_digest, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	SessionID   string
	LearnerID   string
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.SessionID,
		arg.LearnerID,
		arg.TokenDigest,
		arg.ExpiresAt,
	)
	return err
}
