// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: target.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTargetProfile = `-- name: GetTargetProfile :one
SELECT
  test_variant,
  target_overall_band,
  minimum_listening_band,
  minimum_reading_band,
  minimum_writing_band,
  minimum_speaking_band,
  resource_revision,
  updated_at
FROM target_profiles
WHERE learner_id = $1
`

type GetTargetProfileRow struct {
	TestVariant          string
	TargetOverallBand    *float64
	MinimumListeningBand *float64
	MinimumReadingBand   *float64
	MinimumWritingBand   *float64
	MinimumSpeakingBand  *float64
	ResourceRevision     int64
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetTargetProfile(ctx context.Context, learnerID string) (GetTargetProfileRow, error) {
	row := q.db.QueryRow(ctx, getTargetProfile, learnerID)
	var i GetTargetProfileRow
	err := row.Scan(
		&i.TestVariant,
		&i.TargetOverallBand,
		&i.MinimumListeningBand,
		&i.MinimumReadingBand,
		&i.MinimumWritingBand,
		&i.MinimumSpeakingBand,
		&i.ResourceRevision,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTargetProfile = `-- name: InsertTargetProfile :execrows
INSERT INTO target_profiles (
  learner_id,
  test_variant,
  target_overall_band,
  minimum_listening_band,
  minimum_reading_band,
  minimum_writing_band,
  minimum_speaking_band,
  resource_revision
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1)
ON CONFLICT DO NOTHING
`

type InsertTargetProfileParams struct {
	LearnerID            string
	TestVariant          string
	TargetOverallBand    *float64
	MinimumListeningBand *float64
	MinimumReadingBand   *float64
	MinimumWritingBand   *float64
	MinimumSpeakingBand  *float64
}

func (q *Queries) InsertTargetProfile(ctx context.Context, arg InsertTargetProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTargetProfile,
		arg.LearnerID,
		arg.TestVariant,
		arg.TargetOverallBand,
		arg.MinimumListeningBand,
		arg.MinimumReadingBand,
		arg.MinimumWritingBand,
		arg.MinimumSpeakingBand,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTargetProfile = `-- name: UpdateTargetProfile :execrows
UPDATE target_profiles
SET
  test_variant = $2,
  target_overall_band = $3,
  minimum_listening_band = $4,
  minimum_reading_band = $5,
  minimum_writing_band = $6,
  minimum_speaking_band = $7,
  resource_revision = resource_revision + 1,
  updated_at = now()
WHERE learner_id = $1
  AND resource_revision = $8
`

type UpdateTargetProfileParams struct {
	LearnerID            string
	TestVariant          string
	TargetOverallBand    *float64
	MinimumListeningBand *float64
	MinimumReadingBand   *float64
	MinimumWritingBand   *float64
	MinimumSpeakingBand  *float64
	ResourceRevision     int64
}

func (q *Queries) UpdateTargetProfile(ctx context.Context, arg UpdateTargetProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTargetProfile,
		arg.LearnerID,
		arg.TestVariant,
		arg.TargetOverallBand,
		arg.MinimumListeningBand,
		arg.MinimumReadingBand,
		arg.MinimumWritingBand,
		arg.MinimumSpeakingBand,
		arg.ResourceRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
